---
title: "rstudio::conf retweet network"
output: 
  html_notebook:
    code_folding: hide

---

```{r, warning= FALSE, message= FALSE}
library("twitteR")
library("RCurl")
library("bitops")
library("rjson")
library("stringr")
library("grid")
library("plyr")
library("dplyr")
library("purrr")
library("igraph")
library("sna")
library("Matrix")
library("SparseM")
library("plotly")
library("ggnetwork")
```

```{r, message = FALSE, warning = FALSE}
load("twitter_dat.Rda")
tweets <- tbl_df(map_df(dat, as.data.frame))

tweets$reply_to <- sapply(tweets$text, function(tweet) 
    sub("^(.*)?@","",str_extract(tweet,"^((\\.)?(@[[:alnum:]_]*))")))

tweets$retweet_from <- sapply(tweets$text, function(tweet) 
    sub("^(.*)?@","",str_extract(tweet,"^[RM]T (@[[:alnum:]_]*)")))

df_retweets<- data.frame(to = tweets[["screenName"]], 
                        from = tweets[["retweet_from"]])

df_retweets <- na.omit(df_retweets)
  
df_retweets %>%
  group_by(to, from) %>%
  mutate(weight = length(from)) %>%
  filter(weight > 1)->
  df_retweets
```

```{r, echo = FALSE, eval = FALSE}
df_retweets %>%
 group_by(from) %>%
  mutate(weight_sum = sum(weight)) %>%
  ungroup() %>%
  mutate(weight_c = ifelse(weight_sum >= 5, "5+","<5")) ->
  df_retweets
#V(g)$color <- df_retweets$weight_c
```


```{r, message = FALSE, warning = FALSE}

g <- graph.data.frame(df_retweets, directed = TRUE)
V(g)$degree <- centralization.degree(g)$res
V(g)$weighted_degree <- graph.strength(g)
V(g)$text <- V(g)$name

set.seed(916)
df_net <- ggnetwork(g, layout = "fruchtermanreingold", weights="weight", niter=5000, arrow.gap=0)

plot <- ggplot(df_net, aes(x = x, y = y, xend = xend, yend = yend)) +
    geom_edges(size=0.4, alpha=0.25) +
    geom_nodes(aes(size = degree, text = text)) +
    ggtitle("rstudio::conf retweet network") +
    guides(size=FALSE) +
    theme_blank() 

plot %>% ggplotly(tooltip="text")
```

**thank you** http://minimaxir.com/notebooks/interactive-network/ &  http://www.austinwehrwein.com/data-visualization/networks-graph-r-plotly/

